# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='imgActividad/default.jpg', upload_to='imgActividad/')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='VisitasActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'visitactividad',
                'verbose_name_plural': 'visitasactividades',
            },
        ),
        migrations.CreateModel(
            name='VisitasPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ['-fecha'],
                'verbose_name': 'visitaperfil',
                'verbose_name_plural': 'visitasperfiles',
            },
        ),
        migrations.AlterModelManagers(
            name='capsulas',
            managers=[
                ('perfil', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='comentarios',
            managers=[
                ('perfil', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rol',
            managers=[
                ('perfil', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='visitas',
        ),
        migrations.RemoveField(
            model_name='capsulas',
            name='autorizado',
        ),
        migrations.RemoveField(
            model_name='capsulas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='visitas',
        ),
        migrations.AddField(
            model_name='actividad',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capsulas',
            name='imagen',
            field=models.ImageField(default='imgCapsula/default.jpg', upload_to='imgCapsula/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='actividad',
            field=models.ManyToManyField(to='api.Actividad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='actividad',
            field=models.ManyToManyField(to='api.Actividad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitasactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actividad'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actividad'),
        ),
    ]
