# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170207_2245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='capsulas',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='comentarios',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rol',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='capsulas',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil'),
        ),
        migrations.AddField(
            model_name='rol',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Perfil'),
        ),
    ]
